version: '3.9'

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    ports:
      - ${PG_PORT}:5432
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DATABASE}

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
